services:
  prowlarr:
    image: linuxserver/prowlarr
    container_name: prowlarr
    environment:
      - PUID=99
      - PGID=100
      - TZ=${TZ:-America/Toronto}
    ports:
      - 9696:9696
    volumes:
      - prowlarr-config:/config
    networks:
      - media
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.prowlarr.rule=Host(`prowlarr.myhome.local`)"
      - "traefik.http.routers.prowlarr.entrypoints=websecure"
      - "traefik.http.routers.prowlarr.tls=true"
    restart: unless-stopped

volumes:
  prowlarr-config:

networks:
  media:
    external: true
