services:
  recyclarr:
    image: ghcr.io/recyclarr/recyclarr
    container_name: recyclarr
    environment:
      - TZ=America/Toronto
      - SONARR_API_KEY=${SONARR_API_KEY}
      - RADARR_API_KEY=${RADARR_API_KEY}
    volumes:
      - recyclarr-config:/config
    networks:
      - media
    restart: unless-stopped

volumes:
  recyclarr-config:

networks:
  media:
    external: true
