services:
  radarr:
    image: linuxserver/radarr
    container_name: radarr
    environment:
      - PUID=100
      - PGID=100
      - TZ=${TZ:-America/Toronto}
    ports:
      - 7878:7878
    volumes:
      - radarr-config:/config
      - /mnt/media/library:/data
    networks:
      - media
    restart: unless-stopped

volumes:
  radarr-config:

networks:
  media:
    external: true
