services:
  bazarr:
    image: linuxserver/bazarr
    container_name: bazarr
    environment:
      - PUID=99
      - PGID=100
      - TZ=${TZ:-America/Toronto}
    ports:
      - 6767:6767
    volumes:
      - bazarr-config:/config
      - /mnt/media/library:/data
    networks:
      - media
    restart: unless-stopped

volumes:
  bazarr-config:

networks:
  media:
    external: true
