services:
  jellyseerr:
    image: fallenbagel/jellyseerr
    container_name: jellyseerr
    environment:
      - TZ=America/Toronto
    ports:
      - 5055:5055
    volumes:
      - jellyseerr-config:/app/config
    networks:
      - media
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.jellyseerr.rule=Host(`jellyseerr.myhome.local`)"
      - "traefik.http.routers.jellyseerr.entrypoints=websecure"
      - "traefik.http.routers.jellyseerr.tls=true"
    restart: unless-stopped

volumes:
  jellyseerr-config:

networks:
  media:
    external: true
